remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: [Sweet or Savory Analysis]
description: [This is a project for DSC80 at UCSD. It is an analysis of a dataset of recipes and reviews, with the goal of answering the question. Which do people prefer, sweet, or savory recipes?]